rabbitmq:
  #url: "amqp://guest:guest@localhost:5672/" 
  url: "amqp://guest:guest@rabbitmq:5672/"
exchange:
  name: "clearsky.events"
  type: "topic"
queue:
  name: "Orchestrator_Q"
  dlx: "orchestrator.dlq"
bindings:
  - "institution.registered"
  - "user.created"
  - "statistics.viewed"
  - "grades.viewed"
  - "grades.initial.uploaded"
  - "grades.final.uploaded"
  - "credits.avail"
  - "credits.spent"
  - "credits.purchased"
  - "user.login.google"
  - "student.postNewRequest"
  - "student.getRequestStatus"
  - "student.updateInstructorResponse"
  - "instructor.postResponse"
  - "instructor.getRequestsList"
  - "instructor.getRequestInfo"
  - "instructor.insertStudentRequest"
  - "auth.register"
  - "auth.login"
  - "auth.delete"
  - "auth.login.google"