version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: clearSky-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
    networks:
      - clearSky-net

networks:
  clearSky-net:
    driver: bridge
