version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reviewsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./reviewsdb.sql:/docker-entrypoint-initdb.d/reviewsdb.sql

  app:
    build: .
    ports:
      - "8087:8087"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/reviewsdb?sslmode=disable

volumes:
  db_data:
