version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reviewsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/reviewsdb.sql:/docker-entrypoint-initdb.d/reviewsdb.sql
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    restart: on-failure
    ports:
      - "8087:8087"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/reviewsdb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/


volumes:
  db_data:
