# docker-compose.yml
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - backendnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ main port (used by apps)
      - "15672:15672"     # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backendnet
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stats_backend
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - backendnet
    restart: on-failure

networks:
  backendnet:
    driver: bridge
