version: "3.8"

services:

  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER:   ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:     ${DB_NAME}
    ports:
      - "5434:5432"        # map host 5434 → container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  credit_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # override DB_HOST for your app
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
