version: "3.8"
services:

  credits_db:
    image: postgres:14
    container_name: credits_postgres      # unique name!
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:   ${DB_NAME}
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
      - credits_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"                       # avoid host port collision

  rabbitmq:                              # you can keep the same name, it’ll error only if you also run a rabbitmq here
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  credits_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credits_service
    restart: on-failure
    depends_on:
      - credits_db
      - rabbitmq
    env_file: .env
    ports:
      - "8081:8080"                       # if you want a different host port

volumes:
  credits_pgdata:
