version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator
    ports:
      - "8080:8080"          # expose το 8080
    networks:
      - saas-network

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    environment:
      - GO_API_URL=http://orchestrator:8080  
    depends_on:
      - orchestrator
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge