version: '3.8'

services:
  app:
    build: .
    container_name: final_grades
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://finalsdb:27017/final_grades
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=clearSky.events
      - RABBITMQ_ROUTING_KEY=postgrades.final
      - RABBITMQ_CREDIT_INCR_KEY=credits.incr

    depends_on:
      - finalsdb
      - rabbitmq

  finalsdb:
    image: mongo:6.0
    container_name: finalsdb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: unless-stopped
      ports:
        - "5672:5672"     # RabbitMQ AMQP port
        - "15672:15672"   # RabbitMQ management UI
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo_data:
