version: '3.8'

services:
  stats_service:
    build: .
    container_name: stats_service
    restart: unless-stopped
    environment:
      - MYSQL_URI=mysql://user:password@mysql:3306/statsdb
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=clearSky.events
      - RABBITMQ_ROUTING_KEY=postgrades.statistics
      - RABBITMQ_GET_GRADES_KEY=stats.get
      - RABBITMQ_SEND_AVAIL_KEY=stats.avail
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=statsdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mysql_data:
