# docker-compose.yml
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - backendnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stats_backend
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backendnet
    restart: on-failure

networks:
  backendnet:
    driver: bridge
