version: '3.8'

services:
  app:
    build: .
    container_name: initial_grades
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/ingradesdb
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - RABBITMQ_EXCHANGE=clearSky.events
      - RABBITMQ_ROUTING_KEY=postgrades.init
      - RABBITMQ_CREDIT_INCR_KEY=incr.credits
      - MONGO_USER=root
      - MONGO_PASS=2002
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DB=ingradesdb
      - MONGO_AUTH=admin

    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: unless-stopped
      ports:
        - "5672:5672"     # RabbitMQ AMQP port
        - "15672:15672"   # RabbitMQ management UI


volumes:
  mongo_data:
