version: "3.8"
services:

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:   ${DB_NAME}
    volumes:
      # <— mount your init scripts here
      - ./db-init:/docker-entrypoint-initdb.d:ro
      # <— then the data volume
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registration_service
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    env_file: .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
