version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol (backend use)
      - "15672:15672"    # Web UI (browser)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
